spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/new_joiner_auth
spring.datasource.username=postgres
spring.datasource.password=297004

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8081