DELETE FROM checklist_completions;
DELETE FROM checklist_items;

INSERT INTO checklist_items (title, description, order_index) VALUES
    ('Send welcome email', 'Send the welcome email before the start date with login credentials, first-day logistics, and the buddy''s contact info. Send it to the personal inbox and ask them to confirm receipt — everything else on this list starts from there.', 1),
    ('Request laptop and equipment', 'Raise the request for the laptop and any additional assets (monitor, headset, dock) before the start date. Confirm with IT that the request is submitted and flag anything specific to the role so it''s ready on day 1.', 2),
    ('Request access card', 'Submit the access card request with Admin ahead of the start date. Have the new joiner collect the card from reception on the first morning and test it on the main entrance and their floor before settling at their desk.', 3),
    ('Arrange laptop handover', 'Arrange the laptop handover with IT in B2. Once they have it, they log in with the credentials from the welcome email, connect to VPN, and verify they can access Slack, email, and the team''s shared drive.', 4),
    ('Install VPN and MFA', 'Have them install the VPN client from the IT portal and register their device for multi-factor authentication. Make sure they test the connection from off-site once, so they aren''t troubleshooting it the first time they work remotely.', 5),
    ('Request GitHub access', 'Raise a GitHub access request through the IT service portal using their GitHub username. They''re added to the organization first — repository-level permissions come in a separate step.', 6),
    ('Request Jira access', 'Request access to the team''s Jira project so they can see the current sprint board and pick up their first ticket. Once they''re in, check that their account is assigned to the right project role.', 7),
    ('Request SonarQube access', 'SonarQube is where code quality and coverage are tracked on every pull request. Request an account for them and confirm they can view the dashboards for the projects the team owns.', 8),
    ('Submit AWS access request', 'Submit an AWS access request specifying the accounts and environments the role needs. Approve the permission set and make sure they set up MFA on first login.', 9),
    ('Submit Azure access request', 'Submit an Azure access request for the subscriptions and resource groups the team works with. As with AWS, approve the scope and confirm they enable MFA when they first sign in.', 10),
    ('Add to DEV mailing list', 'The DEV distribution list carries release notes, deployment windows, and engineering-wide announcements. Ask IT to add them, then confirm they''re receiving mail on it.', 11),
    ('Add to team channels', 'Tell them which channels matter for the team — usually the team channel, the wider engineering channel, and any project-specific ones. Add them to them, and ask them to set a profile photo and post a short intro in the team channel.', 12),
    ('Add to GitHub teams and repos', 'Once they''re in the GitHub organization, add them to the specific teams and repositories they''ll work on. Ask them to clone one repo to confirm access works, and walk them through the branch protection rules so they know how pull requests and reviews are handled here.', 13),
    ('Complete HR paperwork', 'Send them to the HR desk on the 5th floor to complete their tax forms, emergency contact details, and benefits elections in person. This should be done within the first week to avoid delays in payroll setup.', 14),
    ('Provide bank details', 'Have them provide their bank account information to HR so their salary can be processed. Get this in as early in the month as possible — details received after the payroll cut-off roll over to the following cycle.', 15),
    ('Complete compliance training', 'Assign the mandatory onboarding modules in SuccessFactors — security awareness, code of conduct, and any role-specific courses — and check that they log in to complete them. These are tracked for compliance, so they should be done within the first few weeks.', 16),
    ('Review the handbook', 'Point them to the full handbook in the Company Hub, covering PTO policy, expense guidelines, working hours, and code of conduct. They don''t need to memorize it — one skim so they know what''s in there and where to look it up later.', 17),
    ('Send UK intro email', 'Send a short introduction email to the UK team so they know who has joined, their role, which squad they''re on, and how to reach them. Copy them in so they have the names and email addresses in one place from day one.', 18),
    ('Complete personality assessment', 'Send them the free 16Personalities assessment (about 10 minutes) and ask them to share their result with you and the team. It''s a light conversation starter about working styles — there are no right or wrong outcomes.', 19),
    ('Assign onboarding buddy', 'Name their buddy in the welcome email and brief them beforehand. The buddy is their go-to for questions that feel too small to ask their manager — ask them to message them on day 1 and book 30 minutes that first week.', 20),
    ('Book first 1:1', 'Book a 1:1 with them during their first week to align on expectations for the first 30 days. Add them to the team intro and daily standup invites so they meet the team early.', 21),
    ('Add to team ceremonies', 'Add them to the invites for the team''s recurring ceremonies — sprint planning, refinement, review, and retrospective. Ask their buddy to walk them through how the sprint cycle runs before their first one.', 22);