# Database Configuration - Using Environment Variables
spring.datasource.url=jdbc:postgresql://localhost:5432/${CONTENT_DB_NAME:content_db}
spring.datasource.username=${CONTENT_DB_USER:postgres}
spring.datasource.password=${CONTENT_DB_PASSWORD:02252631}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.initializationFailTimeout=-1
spring.datasource.hikari.connection-test-query=SELECT 1

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=false

jwt.secret=e3GByvQwqLrYV+TgvJpoWGSI/kDpINUEdkNT4N2fkNQ=
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
